- name: Initialize Kubernetes Cluster
  hosts: master
  become: yes
  tasks:
    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=10.10.1.162
      register: init_output
      args:
        creates: /etc/kubernetes/admin.conf # 이미 설정된 경우 건너뜀

    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu

    - name: Install Flannel CNI (Pod Network)
      become: false
      shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command

- name: Join Workers to Cluster
  hosts: workers
  become: yes
  tasks:
    - name: Join the cluster
      shell: "{{ hostvars[groups['master'][0]]['join_command'].stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf # 이미 조인된 경우 건너뜀
